#!/usr/bin/env bats
# lendk check: diagnosis without decrypting (FR31 to FR33).
# shellcheck disable=SC2030,SC2031,SC2329

setup() {
	load helpers/common
	sandbox
	ln -s "$FIXTURES/stub-target" "$SB/bin/stub"
	export LENDK_SHIMS=$SB/shims
	SHIMS=$LENDK_SHIMS
	MAP=$HOME/.config/lendk/map
	HEAD="# map: $MAP"$'\n'"# shims: $SHIMS"$'\n'"# store: $SB/store/env"
	stub_gpg 2.4.4
	export PATH=$SHIMS:$PATH
}

# FR31 across the file: no check call reads a value; only the nested run below does.
teardown() {
	[[ -n ${READS-} ]] || no_reads
}

# map LINE...: write a private map at the default path.
map() {
	mkdir -p "$HOME/.config/lendk" && chmod 700 "$HOME/.config/lendk"
	printf '%s\n' "$@" >"$MAP"
	chmod 600 "$MAP"
}

# keys KEY...: store entries for KEY....
keys() {
	local k
	for k; do printf 'value\n' >"$SB/store/env/$k.gpg"; done
}

# stub_gpg VERSION: gpg and gpg2 on PATH reporting VERSION.
stub_gpg() {
	local g
	for g in gpg gpg2; do
		printf '#!/bin/sh\necho "gpg (GnuPG) %s"\n' "$1" >"$SB/bin/$g"
		chmod +x "$SB/bin/$g"
	done
}

# healthy: a map, its keys and its shims, all in order.
healthy() {
	map '@g K2' 'stub K1 @g'
	keys K1 K2
	run_lendk sync
	assert_eq "$status" 0
}

# no_reads: the backend was never called.
no_reads() { assert_eq "$(compgen -G "$SB/log/pass.*")" ""; }

@test "FR31: check calls no backend read, and an empty value shows as ok" {
	healthy
	: >"$SB/store/env/K1.gpg"
	run_lendk check
	assert_eq "$status" 0
	assert_eq "$stderr" ""
	no_reads
}

@test "FR32: a healthy setup gives headers and ok rows, groups first, sorted, exit 0" {
	map 'zed K1' '@g K2' 'stub K1 @g' '@a K1'
	ln -s "$FIXTURES/stub-target" "$SB/bin/zed"
	keys K1 K2
	run_lendk sync
	run_lendk check
	assert_eq "$output" "$HEAD"$'\n@a\tK1\tok\n@g\tK2\tok\nstub\tK1 @g\tok\nzed\tK1\tok'
	assert_eq "$status" 0
	no_reads
}

@test "FR32: check NAME keeps rows named NAME, holding key NAME, or using group NAME" {
	map '@aws A B' 'tf @aws C' 'stub G'
	ln -s "$FIXTURES/stub-target" "$SB/bin/tf"
	keys A B C G
	run_lendk sync
	run_lendk check A
	assert_eq "$output" "$HEAD"$'\n@aws\tA B\tok\ntf\t@aws C\tok'
	run_lendk check @aws
	assert_eq "$output" "$HEAD"$'\n@aws\tA B\tok\ntf\t@aws C\tok'
	run_lendk check stub C
	assert_eq "$output" "$HEAD"$'\nstub\tG\tok\ntf\t@aws C\tok'
	assert_eq "$status" 0
}

@test "FR32: interactive calls get the full FIX; lendk sync and lendk run -- CMD stay non-interactive" {
	map 'stub K1'
	LENDK_PROMPT=allow run_lendk check
	assert_line "$output" $'stub\tK1\tenv/K1 is not in the store (pass insert env/K1); no shim (lendk sync)'
	run_lendk check
	assert_line "$output" $'stub\tK1\tenv/K1 is not in the store (ask the user); no shim (lendk sync)'
	assert_eq "$status" 1
}

@test "FR33: map violations, on their row or as a problem line" {
	map 'bad! K1' 'stub K1 @nope' 'stub K1'
	keys K1
	run_lendk sync
	run_lendk check
	assert_eq "$output" "$HEAD"$'\n'"# problem: $MAP:1: 'bad!' is not a valid command name (ask the user)"$'\n'"stub	K1 @nope	line 2: group @nope is not defined (ask the user); line 3: stub is mapped twice (ask the user)"
	assert_eq "$status" 1
	LENDK_PROMPT=allow run_lendk check
	assert_line "$output" "# problem: $MAP:1: 'bad!' is not a valid command name (fix the line)"
}

@test "FR33: a missing key" {
	healthy
	rm "$SB/store/env/K2.gpg"
	run_lendk check
	assert_line "$output" $'@g\tK2\tenv/K2 is not in the store (ask the user)'
	assert_line "$output" $'stub\tK1 @g\tenv/K2 is not in the store (ask the user)'
	assert_eq "$status" 1
}

@test "FR33: a command not found" {
	map 'nothere K1'
	keys K1
	run_lendk sync
	run_lendk check
	assert_line "$output" $'nothere\tK1\t'"nothere is not on PATH outside $SHIMS (ask the user)"
	LENDK_PROMPT=allow run_lendk check
	assert_line "$output" $'nothere\tK1\t'"nothere is not on PATH outside $SHIMS (install it, or unmap it: lendk rm nothere)"
	assert_eq "$status" 1
}

@test "FR33: no shim, a stale shim, and a stray shim" {
	healthy
	rm "$SHIMS/stub"
	run_lendk check
	assert_line "$output" $'stub\tK1 @g\tno shim (lendk sync)'
	assert_eq "$status" 1
	run_lendk sync
	printf 'edited\n' >>"$SHIMS/stub"
	run_lendk check
	assert_line "$output" $'stub\tK1 @g\tstale shim (lendk sync)'
	run_lendk sync
	printf '#!/bin/sh\n# lendk shim v1: generated by lendk sync, edits are overwritten\n' >"$SHIMS/old"
	run_lendk check
	assert_eq "$output" "$HEAD"$'\n'"# problem: $SHIMS/old is a stray shim (lendk sync)"$'\n@g\tK2\tok\nstub\tK1 @g\tok'
	assert_eq "$status" 1
}

@test "FR33: foreign files in the shim directory, named like a mapped command or not" {
	healthy
	printf 'mine\n' >"$SHIMS/notes"
	printf '#!/bin/sh\necho mine\n' >"$SHIMS/stub"
	run_lendk check
	assert_eq "$output" "$HEAD"$'\n'"# problem: $SHIMS/notes is not a lendk shim (ask the user)"$'\n@g\tK2\tok\nstub\tK1 @g\t'"$SHIMS/stub is not a lendk shim (ask the user)"
	LENDK_PROMPT=allow run_lendk check
	assert_line "$output" "# problem: $SHIMS/notes is not a lendk shim (move it out of $SHIMS)"
	assert_eq "$status" 1
}

@test "FR33: a shim whose lendk path is not executable" {
	map 'stub K1'
	keys K1
	mkdir "$SB/opt"
	cp "$LENDK" "$SB/opt/lendk"
	LENDK=$SB/opt/lendk run_lendk sync
	chmod -x "$SB/opt/lendk"
	run_lendk check
	assert_line "$output" $'stub\tK1\t'"the shim runs $SB/opt/lendk, which is not executable (lendk sync)"
	assert_eq "$status" 1
}

@test "FR33: unsafe map and shim directory" {
	healthy
	chmod 770 "$SHIMS"
	chmod 660 "$MAP"
	run_lendk check
	assert_eq "$output" "$HEAD"$'\n'"# problem: $MAP is writable by others (ask the user)"$'\n'"# problem: $SHIMS is writable by others (ask the user)"$'\n@g\tK2\tok\nstub\tK1 @g\tok'
	assert_eq "$status" 1
	no_reads
}

@test "FR33: the shim directory is not on PATH" {
	healthy
	PATH=${PATH#"$SHIMS":} run_lendk check
	assert_eq "$output" "$HEAD"$'\n'"# problem: $SHIMS is not on PATH (ask the user)"$'\n@g\tK2\tok\nstub\tK1 @g\tok'
	assert_eq "$status" 1
}

@test "FR33: shadowed, naming the earlier path" {
	healthy
	mkdir "$SB/early"
	ln -s "$FIXTURES/stub-target" "$SB/early/stub"
	PATH=$SB/early:$PATH run_lendk check
	assert_line "$output" $'stub\tK1 @g\t'"shadowed by $SB/early/stub (lendk run -- stub)"
	PATH=$SB/early:$PATH LENDK_PROMPT=allow run_lendk check
	assert_line "$output" $'stub\tK1 @g\t'"shadowed by $SB/early/stub (put $SHIMS first on PATH, or call: lendk run -- stub)"
	assert_eq "$status" 1
}

@test "FR33: a GnuPG below 2.4" {
	healthy
	stub_gpg 2.2.27
	run_lendk check
	assert_line "$output" "# problem: GnuPG 2.2.27 found; lendk needs GnuPG 2.4 or later (ask the user)"
	assert_eq "$status" 1
}

@test "FR33: a mapped key set in the environment, unless lendk injected it" {
	healthy
	K2='set' run_lendk check
	assert_line "$output" $'@g\tK2\tK2 is set in the environment, which overrides the store (ask the user)'
	assert_line "$output" $'stub\tK1 @g\tK2 is set in the environment, which overrides the store (ask the user)'
	assert_eq "$status" 1
	K2='set' LENDK_INJECTED='K1 K2' run_lendk check
	assert_eq "$status" 0
	READS=1
	run_lendk run K1 K2 -- "$LENDK" check
	assert_eq "$status" 0
	assert_line "$output" $'stub\tK1 @g\tok'
}

@test "FR33: exit 1 only when a shown item has a problem" {
	healthy
	map '@g K2' 'stub K1 @g' 'other K3'
	run_lendk check stub
	assert_eq "$status" 0
	run_lendk check other
	assert_eq "$status" 1
}

@test "FR33: a shim that lost its mode 0755 is stale" {
	healthy
	chmod 644 "$SHIMS/stub"
	run_lendk check
	assert_line "$output" $'stub\tK1 @g\tstale shim (lendk sync)'
	assert_eq "$status" 1
}
