#!/usr/bin/env bats
# lendk sync: shims (FR29, FR30), the whole-map reader (FR23) and the shim directory rules (FR28).
# shellcheck disable=SC2016,SC2030,SC2031

setup() {
	load helpers/common
	sandbox
	ln -s "$FIXTURES/stub-target" "$SB/bin/stub"
	ln -s "$FIXTURES/stub-target" "$SB/bin/other"
	export LENDK_SHIMS=$SB/shims K1=one
	MAP=$HOME/.config/lendk/map
}

# map LINE...: write a private map at the default path.
map() {
	mkdir -p "$HOME/.config/lendk" && chmod 700 "$HOME/.config/lendk"
	printf '%s\n' "$@" >"$MAP"
	chmod 600 "$MAP"
}

# expected_shim LENDK CMD: FR29's text for CMD with lendk at LENDK.
expected_shim() {
	printf '%s\n' '#!/bin/sh' '# lendk shim v1: generated by lendk sync, edits are overwritten' "lendk='${1//\'/\'\\\'\'}'" \
		"[ -x \"\$lendk\" ] || { echo \"lendk: lendk-missing: \$lendk is missing, so $2 did not run. The user must reinstall lendk from its project repository, then run: lendk sync\" >&2; exit 127; }" \
		"exec \"\$lendk\" run -- '$2' \"\$@\""
}

# sums: cksum and name of every file in the shim directory.
sums() { (cd "$LENDK_SHIMS" && cksum -- *); }

@test "FR29: sync writes one shim per mapped command, mode 0755, naming lendk by its invoked path" {
	map 'stub K1' '@g K1' 'other @g'
	mkdir "$SB/link"
	ln -s "$LENDK" "$SB/link/lendk"
	cd "$SB"
	LENDK=./link/lendk run_lendk sync
	assert_eq "$status" 0
	assert_eq "$stderr" ""
	assert_eq "$(ls "$LENDK_SHIMS")" $'other\nstub'
	assert_eq "$(cat "$LENDK_SHIMS/stub")" "$(expected_shim "$SB/link/lendk" stub)"
	assert_eq "$(cat "$LENDK_SHIMS/other")" "$(expected_shim "$SB/link/lendk" other)"
	[[ $(ls -ln "$LENDK_SHIMS/stub") == -rwxr-xr-x* ]]
	PATH=$LENDK_SHIMS:$PATH stub a 'b c'
	local logs=("$SB"/log/target.*)
	assert_eq "$(tr '\0' ' ' <"${logs[0]}/argv")" "a b c "
	tr '\0' '\n' <"${logs[0]}/env" | grep -qx 'K1=one'
}

@test "FR29: a lendk path holding a single quote is escaped, and the shim runs" {
	map 'stub K1'
	mkdir "$SB/it's"
	cp "$LENDK" "$SB/it's/lendk"
	LENDK="$SB/it's/lendk" run_lendk sync
	assert_eq "$status" 0
	assert_eq "$(cat "$LENDK_SHIMS/stub")" "$(expected_shim "$SB/it's/lendk" stub)"
	"$LENDK_SHIMS/stub"
	[[ -n $(compgen -G "$SB/log/target.*") ]]
}

@test "FR29: shims survive a versioned upgrade behind a stable symlink" {
	map 'stub K1'
	mkdir -p "$SB/opt/v1" "$SB/opt/v2" "$SB/local/bin"
	cp "$LENDK" "$SB/opt/v1/lendk"
	cp "$LENDK" "$SB/opt/v2/lendk"
	ln -s ../../opt/v1/lendk "$SB/local/bin/lendk"
	LENDK=$SB/local/bin/lendk run_lendk sync
	assert_eq "$status" 0
	local before
	before=$(sums)
	rm "$SB/opt/v1/lendk" && ln -sfn ../../opt/v2/lendk "$SB/local/bin/lendk"
	"$LENDK_SHIMS/stub"
	[[ -n $(compgen -G "$SB/log/target.*") ]]
	LENDK=$SB/local/bin/lendk run_lendk sync
	assert_eq "$(sums)" "$before"
}

@test "FR29: a shim whose lendk is gone gives lendk-missing, exit 127" {
	map 'stub K1'
	mkdir "$SB/opt"
	cp "$LENDK" "$SB/opt/lendk"
	LENDK=$SB/opt/lendk run_lendk sync
	rm "$SB/opt/lendk"
	local st=0 err
	err=$("$LENDK_SHIMS/stub" 2>&1) || st=$?
	assert_eq "$st" 127
	assert_eq "$err" "lendk: lendk-missing: $SB/opt/lendk is missing, so stub did not run. The user must reinstall lendk from its project repository, then run: lendk sync"
	[[ $err =~ ^lendk:\ lendk-missing:\ .+\.\ .+$ ]]
}

@test "FR30: a second sync changes no byte" {
	map 'stub K1' 'other K1'
	run_lendk sync
	local before
	before=$(sums)
	local stamp=$SB/stamp
	touch "$stamp"
	sleep 1.1
	run_lendk sync
	assert_eq "$status" 0
	assert_eq "$(sums)" "$before"
	run_lendk sync
	assert_eq "$(find "$LENDK_SHIMS" -newer "$stamp")" ""
}

@test "FR30: sync rewrites a stale shim and deletes only marker-bearing shims of unmapped commands" {
	map 'stub K1' 'other K1'
	run_lendk sync
	printf '#!/bin/sh\n# lendk shim v0: old\nexit 3\n' >"$LENDK_SHIMS/gone"
	printf 'edited\n' >>"$LENDK_SHIMS/stub"
	printf '#!/bin/sh\necho mine\n' >"$LENDK_SHIMS/mine"
	map 'stub K1'
	run_lendk sync
	assert_eq "$status" 0
	assert_eq "$stderr" "lendk: notice: $LENDK_SHIMS/mine is not a lendk shim, so sync leaves it."
	assert_eq "$(ls "$LENDK_SHIMS")" $'mine\nstub'
	assert_eq "$(cat "$LENDK_SHIMS/stub")" "$(expected_shim "$LENDK" stub)"
	assert_eq "$(cat "$LENDK_SHIMS/mine")" $'#!/bin/sh\necho mine'
}

@test "FR30: a foreign file named like a mapped command stays and gives write after the other shims" {
	map 'other K1' 'stub K1'
	mkdir -m 700 "$LENDK_SHIMS"
	printf '#!/bin/sh\necho mine\n' >"$LENDK_SHIMS/stub"
	chmod 700 "$LENDK_SHIMS/stub"
	LENDK_PROMPT=allow run_lendk sync
	assert_eq "$stderr" "lendk: write: $LENDK_SHIMS/stub: is not a lendk shim, so sync leaves it. Fix it, then run: lendk sync"
	assert_class write 125
	assert_eq "$(cat "$LENDK_SHIMS/stub")" $'#!/bin/sh\necho mine'
	[[ $(ls -ln "$LENDK_SHIMS/stub") == -rwx------* ]]
	assert_eq "$(cat "$LENDK_SHIMS/other")" "$(expected_shim "$LENDK" other)"
}

@test "FR23: sync writes shims for every valid command line, then reports each violation" {
	map '<<<<<<< HEAD' 'stub K1 @nope' 'stub K1' 'bad! K1' '@g @h' 'gpg K1' 'other K1' 'empty' '>>>>>>> branch'
	run_lendk sync
	assert_eq "$stderr" "$(printf 'lendk: map: %s. Stop and ask the user.\n' \
		"$MAP:1: '<<<<<<<' is not a valid command name" \
		"$MAP:2: group @nope is not defined" \
		"$MAP:3: stub is mapped twice" \
		"$MAP:4: 'bad!' is not a valid command name" \
		"$MAP:5: group @g holds @h; groups hold keys only" \
		"$MAP:6: gpg is lendk's own runtime and cannot be mapped" \
		"$MAP:8: empty maps no keys" \
		"$MAP:9: '>>>>>>>' is not a valid command name")"
	assert_class map 125
	assert_eq "$(ls "$LENDK_SHIMS")" $'empty\nother\nstub'
}

@test "FR23: several violations on one line are reported in word order" {
	map 'stub PATH 9x @nope HOME'
	run_lendk sync
	assert_eq "$stderr" "$(printf 'lendk: map: %s. Stop and ask the user.\n' \
		"$MAP:1: key 'PATH' is denied" "$MAP:1: '9x' is not a valid key name" \
		"$MAP:1: key 'HOME' is denied" "$MAP:1: group @nope is not defined")"
}

@test "FR23: sync without a map writes no shim and removes the old ones" {
	map 'stub K1'
	run_lendk sync
	rm "$MAP"
	run_lendk sync
	assert_eq "$status" 0
	assert_eq "$(ls -A "$LENDK_SHIMS")" ""
}

@test "FR28: sync creates the shim directory 0700 under any umask" {
	map 'stub K1'
	export LENDK_SHIMS=$SB/data/lendk/shims
	umask 000
	run_lendk sync
	assert_eq "$status" 0
	[[ $(ls -ldn "$LENDK_SHIMS") == drwx------* ]]
	[[ $(ls -ldn "$SB/data/lendk") == drwx------* ]]
	[[ $(ls -ln "$LENDK_SHIMS/stub") == -rwxr-xr-x* ]]
}

@test "FR28: sync gives unsafe for a shim directory open to others or a map open to others" {
	map 'stub K1'
	mkdir -m 700 "$LENDK_SHIMS"
	chmod 770 "$LENDK_SHIMS"
	run_lendk sync
	assert_eq "$stderr" "lendk: unsafe: $LENDK_SHIMS is writable by others. Stop and ask the user."
	assert_class unsafe 125
	assert_eq "$(ls -A "$LENDK_SHIMS")" ""
	chmod 700 "$LENDK_SHIMS"
	chmod 660 "$MAP"
	run_lendk sync
	assert_eq "$stderr" "lendk: unsafe: $MAP is writable by others. Stop and ask the user."
	assert_class unsafe 125
	assert_eq "$(ls -A "$LENDK_SHIMS")" ""
}

@test "FR28: sync gives unsafe for a shim directory owned by another user" {
	[[ $(id -u) != 0 ]] || skip "root owns every path"
	map 'stub K1'
	LENDK_SHIMS=/ run_lendk sync
	assert_eq "$stderr" "lendk: unsafe: / is owned by another user. Stop and ask the user."
	assert_class unsafe 125
}

@test "FR30: sync restores a shim's mode 0755, and removes a killed sync's temporary file" {
	map 'stub K1'
	run_lendk sync
	chmod 644 "$LENDK_SHIMS/stub"
	: >"$LENDK_SHIMS/.lendk-sync.99999999"
	run_lendk sync
	assert_eq "$status" 0
	assert_eq "$stderr" ""
	[[ $(ls -ln "$LENDK_SHIMS/stub") == -rwxr-xr-x* ]]
	assert_eq "$(ls -A "$LENDK_SHIMS")" stub
}

@test "FR5: a shim directory other than this call's is skipped, so a shim never runs itself" {
	map 'stub K1'
	run_lendk sync
	local shims=$LENDK_SHIMS
	PATH=$shims:$PATH LENDK_SHIMS='' timeout 10 "$shims/stub"
	[[ -n $(compgen -G "$SB/log/target.*") ]]
}
