#!/usr/bin/env bats
# lend sync: shims (FR29, FR30), the whole-map reader (FR23) and the shim directory rules (FR28).
# shellcheck disable=SC2016,SC2030,SC2031

setup() {
	load helpers/common
	sandbox
	ln -s "$FIXTURES/stub-target" "$SB/bin/stub"
	ln -s "$FIXTURES/stub-target" "$SB/bin/other"
	export LEND_SHIMS=$SB/shims K1=one
	MAP=$HOME/.config/lend/map
}

# map LINE...: write a private map at the default path.
map() {
	mkdir -p "$HOME/.config/lend" && chmod 700 "$HOME/.config/lend"
	printf '%s\n' "$@" >"$MAP"
	chmod 600 "$MAP"
}

# expected_shim LEND CMD: FR29's text for CMD with lend at LEND.
expected_shim() {
	printf '%s\n' '#!/bin/sh' '# lend shim v1: generated by lend sync, edits are overwritten' "lend='${1//\'/\'\\\'\'}'" \
		"[ -x \"\$lend\" ] || { echo \"lend: lend-missing: \$lend is missing, so $2 did not run. The user must reinstall lend from its project repository, then run: lend sync\" >&2; exit 127; }" \
		"exec \"\$lend\" run -- '$2' \"\$@\""
}

# sums: cksum and name of every file in the shim directory.
sums() { (cd "$LEND_SHIMS" && cksum -- *); }

@test "FR29: sync writes one shim per mapped command, mode 0755, naming lend by its invoked path" {
	map 'stub K1' '@g K1' 'other @g'
	mkdir "$SB/link"
	ln -s "$LEND" "$SB/link/lend"
	cd "$SB"
	LEND=./link/lend run_lend sync
	assert_eq "$status" 0
	assert_eq "$stderr" ""
	assert_eq "$(ls "$LEND_SHIMS")" $'other\nstub'
	assert_eq "$(cat "$LEND_SHIMS/stub")" "$(expected_shim "$SB/link/lend" stub)"
	assert_eq "$(cat "$LEND_SHIMS/other")" "$(expected_shim "$SB/link/lend" other)"
	[[ $(ls -ln "$LEND_SHIMS/stub") == -rwxr-xr-x* ]]
	PATH=$LEND_SHIMS:$PATH stub a 'b c'
	local logs=("$SB"/log/target.*)
	assert_eq "$(tr '\0' ' ' <"${logs[0]}/argv")" "a b c "
	tr '\0' '\n' <"${logs[0]}/env" | grep -qx 'K1=one'
}

@test "FR29: a lend path holding a single quote is escaped, and the shim runs" {
	map 'stub K1'
	mkdir "$SB/it's"
	cp "$LEND" "$SB/it's/lend"
	LEND="$SB/it's/lend" run_lend sync
	assert_eq "$status" 0
	assert_eq "$(cat "$LEND_SHIMS/stub")" "$(expected_shim "$SB/it's/lend" stub)"
	"$LEND_SHIMS/stub"
	[[ -n $(compgen -G "$SB/log/target.*") ]]
}

@test "FR29: shims survive a versioned upgrade behind a stable symlink" {
	map 'stub K1'
	mkdir -p "$SB/opt/v1" "$SB/opt/v2" "$SB/local/bin"
	cp "$LEND" "$SB/opt/v1/lend"
	cp "$LEND" "$SB/opt/v2/lend"
	ln -s ../../opt/v1/lend "$SB/local/bin/lend"
	LEND=$SB/local/bin/lend run_lend sync
	assert_eq "$status" 0
	local before
	before=$(sums)
	rm "$SB/opt/v1/lend" && ln -sfn ../../opt/v2/lend "$SB/local/bin/lend"
	"$LEND_SHIMS/stub"
	[[ -n $(compgen -G "$SB/log/target.*") ]]
	LEND=$SB/local/bin/lend run_lend sync
	assert_eq "$(sums)" "$before"
}

@test "FR29: a shim whose lend is gone gives lend-missing, exit 127" {
	map 'stub K1'
	mkdir "$SB/opt"
	cp "$LEND" "$SB/opt/lend"
	LEND=$SB/opt/lend run_lend sync
	rm "$SB/opt/lend"
	local st=0 err
	err=$("$LEND_SHIMS/stub" 2>&1) || st=$?
	assert_eq "$st" 127
	assert_eq "$err" "lend: lend-missing: $SB/opt/lend is missing, so stub did not run. The user must reinstall lend from its project repository, then run: lend sync"
	[[ $err =~ ^lend:\ lend-missing:\ .+\.\ .+$ ]]
}

@test "FR30: a second sync changes no byte" {
	map 'stub K1' 'other K1'
	run_lend sync
	local before
	before=$(sums)
	local stamp=$SB/stamp
	touch "$stamp"
	sleep 1.1
	run_lend sync
	assert_eq "$status" 0
	assert_eq "$(sums)" "$before"
	run_lend sync
	assert_eq "$(find "$LEND_SHIMS" -newer "$stamp")" ""
}

@test "FR30: sync rewrites a stale shim and deletes only marker-bearing shims of unmapped commands" {
	map 'stub K1' 'other K1'
	run_lend sync
	printf '#!/bin/sh\n# lend shim v0: old\nexit 3\n' >"$LEND_SHIMS/gone"
	printf 'edited\n' >>"$LEND_SHIMS/stub"
	printf '#!/bin/sh\necho mine\n' >"$LEND_SHIMS/mine"
	map 'stub K1'
	run_lend sync
	assert_eq "$status" 0
	assert_eq "$stderr" "lend: notice: $LEND_SHIMS/mine is not a lend shim, so sync leaves it."
	assert_eq "$(ls "$LEND_SHIMS")" $'mine\nstub'
	assert_eq "$(cat "$LEND_SHIMS/stub")" "$(expected_shim "$LEND" stub)"
	assert_eq "$(cat "$LEND_SHIMS/mine")" $'#!/bin/sh\necho mine'
}

@test "FR30: a foreign file named like a mapped command stays and gives write after the other shims" {
	map 'other K1' 'stub K1'
	mkdir -m 700 "$LEND_SHIMS"
	printf '#!/bin/sh\necho mine\n' >"$LEND_SHIMS/stub"
	chmod 700 "$LEND_SHIMS/stub"
	LEND_PROMPT=allow run_lend sync
	assert_eq "$stderr" "lend: write: $LEND_SHIMS/stub: is not a lend shim, so sync leaves it. Fix it, then run: lend sync"
	assert_class write 125
	assert_eq "$(cat "$LEND_SHIMS/stub")" $'#!/bin/sh\necho mine'
	[[ $(ls -ln "$LEND_SHIMS/stub") == -rwx------* ]]
	assert_eq "$(cat "$LEND_SHIMS/other")" "$(expected_shim "$LEND" other)"
}

@test "FR23: sync writes shims for every valid command line, then reports each violation" {
	map '<<<<<<< HEAD' 'stub K1 @nope' 'stub K1' 'bad! K1' '@g @h' 'gpg K1' 'other K1' 'empty' '>>>>>>> branch'
	run_lend sync
	assert_eq "$stderr" "$(printf 'lend: map: %s. Stop and ask the user.\n' \
		"$MAP:1: '<<<<<<<' is not a valid command name" \
		"$MAP:2: group @nope is not defined" \
		"$MAP:3: stub is mapped twice" \
		"$MAP:4: 'bad!' is not a valid command name" \
		"$MAP:5: group @g holds @h; groups hold keys only" \
		"$MAP:6: gpg is lend's own runtime and cannot be mapped" \
		"$MAP:8: empty maps no keys" \
		"$MAP:9: '>>>>>>>' is not a valid command name")"
	assert_class map 125
	assert_eq "$(ls "$LEND_SHIMS")" $'empty\nother\nstub'
}

@test "FR23: sync without a map writes no shim and removes the old ones" {
	map 'stub K1'
	run_lend sync
	rm "$MAP"
	run_lend sync
	assert_eq "$status" 0
	assert_eq "$(ls -A "$LEND_SHIMS")" ""
}

@test "FR28: sync creates the shim directory 0700 under any umask" {
	map 'stub K1'
	export LEND_SHIMS=$SB/data/lend/shims
	umask 000
	run_lend sync
	assert_eq "$status" 0
	[[ $(ls -ldn "$LEND_SHIMS") == drwx------* ]]
	[[ $(ls -ldn "$SB/data/lend") == drwx------* ]]
	[[ $(ls -ln "$LEND_SHIMS/stub") == -rwxr-xr-x* ]]
}

@test "FR28: sync gives unsafe for a shim directory open to others or a map open to others" {
	map 'stub K1'
	mkdir -m 700 "$LEND_SHIMS"
	chmod 770 "$LEND_SHIMS"
	run_lend sync
	assert_eq "$stderr" "lend: unsafe: $LEND_SHIMS is writable by others. Stop and ask the user."
	assert_class unsafe 125
	assert_eq "$(ls -A "$LEND_SHIMS")" ""
	chmod 700 "$LEND_SHIMS"
	chmod 660 "$MAP"
	run_lend sync
	assert_eq "$stderr" "lend: unsafe: $MAP is writable by others. Stop and ask the user."
	assert_class unsafe 125
	assert_eq "$(ls -A "$LEND_SHIMS")" ""
}

@test "FR28: sync gives unsafe for a shim directory owned by another user" {
	[[ $(id -u) != 0 ]] || skip "root owns every path"
	map 'stub K1'
	LEND_SHIMS=/ run_lend sync
	assert_eq "$stderr" "lend: unsafe: / is owned by another user. Stop and ask the user."
	assert_class unsafe 125
}
