#!/bin/sh
# lendk installer: curl -fsSL https://raw.githubusercontent.com/v-bonilla/lendk/main/install.sh | bash
# SPDX-License-Identifier: MIT
#
# POSIX sh, so it runs under dash, busybox sh and macOS's bash 3.2. Progress goes to stdout; except
# for --help, the last line is always "lendk-install: ok: TEXT" or "lendk-install: CLASS: TEXT", CLASS
# being one of usage, unsupported-os, missing-deps, download, checksum, install or path. Exit 0 on ok,
# 2 on usage, else 1.
# LENDK_INSTALL_BASE_URL replaces https://github.com/v-bonilla/lendk/releases, for tests and mirrors:
# the installer reads BASE/latest/download/ASSET, or BASE/download/vX.Y.Z/ASSET with --version, for
# the assets lendk.tar.gz and SHA256SUMS. It must be https:// or file://; file:// is copied.
# All work happens in functions and main runs on the last line, so a truncated download does nothing.
# shellcheck disable=SC2015,SC2016 # A && B || fail chains; code for other shells
set -u

open_mark='# >>> lendk-install >>>'
close_mark='# <<< lendk-install <<<'
lendk_mark='# lendk: give API keys stored in pass to the commands that need them.'
shim_mark='# lendk shim v1: generated by lendk sync, edits are overwritten'
tmp=

say() { printf '%s\n' "$*"; }
cleanup() { [ -z "$tmp" ] || rm -rf "$tmp"; }
# finish CLASS TEXT: the final line, then exit.
finish() {
	trap - HUP INT TERM
	cleanup
	printf 'lendk-install: %s: %s\n' "$1" "$2"
	case $1 in ok) exit 0 ;; usage) exit 2 ;; *) exit 1 ;; esac
}
# sq WORD: WORD quoted for sh.
sq() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"; }

usage() {
	cat <<'EOF'
Usage: install.sh [OPTION...]
Install lendk from its latest GitHub release into PREFIX/bin, without root.

  --version X.Y.Z    install release X.Y.Z instead of the latest
  --prefix DIR       install into DIR/bin (default ~/.local)
  --yes              never prompt (also implied when stdin is not a terminal)
  --install-deps     run the package manager command for missing dependencies
  --no-modify-path   leave login files and the environment.d file alone
  --skill-dir DIR    copy the lendk agent skill to DIR/lendk
  --uninstall        remove what this installer added, never the map or the pass store
  --help             print this help, and nothing else

Except with --help, the last line of output is "lendk-install: ok: TEXT" or
"lendk-install: CLASS: TEXT".
EOF
}

parse() {
	version=
	prefix=
	yes=0
	install_deps=0
	modify_path=1
	skill_dir=
	uninstall=0
	while [ $# -gt 0 ]; do
		case $1 in
		--version | --prefix | --skill-dir)
			[ $# -ge 2 ] || finish usage "$1 needs a value; see --help"
			case $1 in
			--version) version=$2 ;;
			--prefix) prefix=$2 ;;
			--skill-dir) skill_dir=$2 ;;
			esac
			shift
			;;
		--yes) yes=1 ;;
		--install-deps) install_deps=1 ;;
		--no-modify-path) modify_path=0 ;;
		--uninstall) uninstall=1 ;;
		--help) usage; exit 0 ;;
		*) finish usage "unknown option '$1'; see --help" ;;
		esac
		shift
	done
	case ${HOME-} in /*) ;; *) finish usage "HOME is not an absolute path; set HOME and rerun" ;; esac
	[ -n "$prefix" ] || prefix=$HOME/.local
	case $version in '' | [0-9]*.[0-9]*.[0-9]*) ;; *) finish usage "--version takes X.Y.Z, not '$version'" ;; esac
	case $version in *[!0-9.]*) finish usage "--version takes X.Y.Z, not '$version'" ;; esac
	case $prefix in /*) ;; *) finish usage "--prefix takes an absolute path, not '$prefix'" ;; esac
	case $skill_dir in '' | /*) ;; *) finish usage "--skill-dir takes an absolute path, not '$skill_dir'" ;; esac
	base=${LENDK_INSTALL_BASE_URL:-https://github.com/v-bonilla/lendk/releases}
	case $base in https://* | file:///*) ;; *) finish usage "LENDK_INSTALL_BASE_URL must start with https:// or file:///, not '$base'" ;; esac
	[ -t 0 ] || yes=1
}

setup() {
	os=$(uname -s)
	case $os in Linux | Darwin) ;; *) finish unsupported-os "$os is not supported; lendk runs on Linux and macOS" ;; esac
	bin=$prefix/bin/lendk
	config=$HOME/.config
	case ${XDG_CONFIG_HOME-} in /*) config=$XDG_CONFIG_HOME ;; esac
	envd=$config/environment.d/99-lendk.conf
	tmp=$(mktemp -d "${TMPDIR:-/tmp}/lendk-install.XXXXXX") || finish install "cannot create a temporary directory"
}

# login_files: the files the installer edits, one per line: the POSIX login file, plus ~/.zshenv on
# zsh, plus ~/.zprofile for zsh on macOS, since path_helper reorders PATH after ~/.zshenv.
login_files() {
	if [ -f "$HOME/.bash_profile" ]; then say "$HOME/.bash_profile"; else say "$HOME/.profile"; fi
	user_shell=${SHELL:-}
	[ -n "$user_shell" ] || { [ "$os" = Darwin ] && user_shell=zsh; }
	case ${user_shell##*/} in zsh) say "$HOME/.zshenv" ;; esac
	case ${user_shell##*/} in zsh) [ "$os" != Darwin ] || say "$HOME/.zprofile" ;; esac
}

# strip_block FILE OUT: FILE without the installer's blocks, written to OUT.
strip_block() {
	sed "/^$open_mark\$/,/^$close_mark\$/d" "$1" >"$2"
}

# replace_file FILE NEW: FILE gets NEW's content in place, keeping its inode, mode and symlinks.
replace_file() {
	cat "$2" >"$1"
}

uninstall() {
	for f in "$HOME/.profile" "$HOME/.bash_profile" "$HOME/.zshenv" "$HOME/.zprofile"; do
		[ -f "$f" ] && grep -qxF "$open_mark" "$f" || continue
		strip_block "$f" "$tmp/f" && replace_file "$f" "$tmp/f" || finish path "cannot edit $f"
		say "removed the lendk-install block from $f"
	done
	if [ -f "$envd" ] && [ "$(sed -n 1p "$envd")" = '# >>> lendk >>>' ]; then
		rm -f "$envd" && say "removed $envd"
	fi
	shims=${LENDK_SHIMS:-}
	data=
	if [ -z "$shims" ]; then
		case ${XDG_DATA_HOME-} in /*) data=$XDG_DATA_HOME/lendk ;; *) data=$HOME/.local/share/lendk ;; esac
		shims=$data/shims
	fi
	for f in "$shims"/*; do
		[ -f "$f" ] && [ "$(sed -n 2p "$f")" = "$shim_mark" ] && rm -f "$f" && say "removed shim $f"
	done
	rmdir "$shims" 2>/dev/null
	[ -z "$data" ] || rmdir "$data" 2>/dev/null
	if [ -n "$skill_dir" ] && [ -f "$skill_dir/lendk/SKILL.md" ] && grep -qx 'name: lendk' "$skill_dir/lendk/SKILL.md"; then
		rm -rf "$skill_dir/lendk" && say "removed $skill_dir/lendk"
	fi
	if [ -f "$bin" ] && [ ! -L "$bin" ] && [ "$(sed -n 2p "$bin")" = "$lendk_mark" ]; then
		rm -f "$bin" && say "removed $bin"
	elif [ -e "$bin" ] || [ -L "$bin" ]; then
		finish install "$bin is not a file the installer wrote, so it stays"
	fi
	finish ok "lendk uninstalled from $prefix; the map and the pass store are untouched"
}

# bash_ok BASH: BASH is bash 4.4 or later.
bash_ok() {
	"$1" -c '[ "${BASH_VERSINFO[0]}" -gt 4 ] || { [ "${BASH_VERSINFO[0]}" -eq 4 ] && [ "${BASH_VERSINFO[1]}" -ge 4 ]; }' 2>/dev/null
}

# need WHAT APT DNF PACMAN ZYPPER APK BREW: record WHAT as missing and its package for this manager.
need() {
	missing="$missing $1"
	case $pm in
	apt-get) pkgs="$pkgs $2" ;;
	dnf) pkgs="$pkgs $3" ;;
	pacman) pkgs="$pkgs $4" ;;
	zypper) pkgs="$pkgs $5" ;;
	apk) pkgs="$pkgs $6" ;;
	brew) pkgs="$pkgs $7" ;;
	esac
}

# detect: sets good_bash, env_bash_ok, the missing list and the package names it needs.
detect() {
	missing=
	pkgs=
	good_bash=
	env_bash_ok=0
	b=$(command -v bash 2>/dev/null) && bash_ok "$b" && env_bash_ok=1
	old_ifs=$IFS
	IFS=:
	for d in $PATH /opt/homebrew/bin /usr/local/bin; do
		[ -n "$d" ] && [ -x "$d/bash" ] && bash_ok "$d/bash" && { good_bash=$d/bash; break; }
	done
	IFS=$old_ifs
	[ -n "$good_bash" ] || need 'bash>=4.4' bash bash bash bash bash bash
	gpg_ok=0
	for g in gpg2 gpg; do
		command -v "$g" >/dev/null 2>&1 || continue
		v=$("$g" --version 2>/dev/null | sed -n '1s/.* //p')
		maj=${v%%.*}
		min=${v#*.}
		min=${min%%.*}
		case $maj$min in '' | *[!0-9]*) continue ;; esac
		if [ "$maj" -gt 2 ] || { [ "$maj" -eq 2 ] && [ "$min" -ge 4 ]; }; then gpg_ok=1; break; fi
	done
	[ "$gpg_ok" = 1 ] || need 'gnupg>=2.4' gnupg gnupg2 gnupg gpg2 gnupg gnupg
	command -v pass >/dev/null 2>&1 || need pass pass pass pass password-store pass pass
	command -v curl >/dev/null 2>&1 || command -v wget >/dev/null 2>&1 || need curl curl curl curl curl curl curl
	command -v tar >/dev/null 2>&1 || need tar tar tar tar tar tar gnu-tar
	command -v sha256sum >/dev/null 2>&1 || command -v shasum >/dev/null 2>&1 || need sha256sum coreutils coreutils coreutils coreutils coreutils coreutils
}

# pm_cmd SUDO: the command installing pkgs, refreshing the package index first where needed.
pm_cmd() {
	case $pm in
	apt-get) say "${1}apt-get update && ${1}apt-get install -y --no-install-recommends$pkgs" ;;
	dnf) say "${1}dnf install -y --setopt=install_weak_deps=False$pkgs" ;;
	pacman) say "${1}pacman -Sy --needed --noconfirm$pkgs" ;;
	zypper) say "${1}zypper --non-interactive install --no-recommends$pkgs" ;;
	apk) say "${1}apk add --no-cache$pkgs" ;;
	brew) say "brew install$pkgs" ;;
	esac
}

deps() {
	pm=
	if [ "$os" = Darwin ]; then
		command -v brew >/dev/null 2>&1 && pm=brew
	else
		for m in apt-get dnf pacman zypper apk brew; do
			command -v "$m" >/dev/null 2>&1 && { pm=$m; break; }
		done
	fi
	sudo=
	[ "$pm" = brew ] || [ "$(id -u)" = 0 ] || sudo='sudo '
	detect
	[ -n "$missing" ] || { say "found bash 4.4 or later at $good_bash"; return 0; }
	[ -n "$pm" ] || finish missing-deps "missing:$missing; no supported package manager found, install them by hand"
	hint=$(pm_cmd "$sudo")
	say "missing:$missing"
	[ "$install_deps" = 1 ] || finish missing-deps "missing:$missing; run: $hint (or rerun with --install-deps)"
	if [ "$yes" = 0 ]; then
		printf 'Run "%s"? [y/N] ' "$hint"
		read -r answer || answer=
		case $answer in y | Y | yes) ;; *) finish missing-deps "missing:$missing; run: $hint" ;; esac
		cmd=$hint
	else
		# Without a terminal sudo cannot ask for a password, so it must fail instead of waiting.
		cmd=$(pm_cmd "${sudo:+sudo -n }")
	fi
	say "running: $cmd"
	# Under curl | sh the script arrives on stdin, so the command must not read it.
	if [ -t 0 ]; then sh -c "$cmd"; else sh -c "$cmd" </dev/null; fi ||
		finish missing-deps "'$cmd' failed; missing:$missing; run it by hand in a terminal${sudo:+ (sudo -v first if sudo asks for a password)}: $hint"
	detect
	[ -z "$missing" ] || finish missing-deps "still missing after '$cmd':$missing"
	say "found bash 4.4 or later at $good_bash"
}

# fetch URL OUT: https only, except file:// under LENDK_INSTALL_BASE_URL.
fetch() {
	case $1 in
	file://*) cp "${1#file://}" "$2" 2>/dev/null ;;
	https://*)
		if command -v curl >/dev/null 2>&1; then
			curl -fsSL --proto '=https' --tlsv1.2 -o "$2" "$1"
		elif wget --help 2>&1 | grep -q -e --https-only; then
			wget -q --https-only -O "$2" "$1"
		else
			wget -q -O "$2" "$1"
		fi
		;;
	*) return 1 ;;
	esac
}

download() {
	if [ -n "$version" ]; then url=$base/download/v$version; else url=$base/latest/download; fi
	say "downloading $url/lendk.tar.gz"
	fetch "$url/lendk.tar.gz" "$tmp/lendk.tar.gz" || finish download "cannot download $url/lendk.tar.gz"
	fetch "$url/SHA256SUMS" "$tmp/SHA256SUMS" || finish download "cannot download $url/SHA256SUMS"
	want=$(sed -n 's/^\([0-9a-f]\{64\}\)  *\*\{0,1\}lendk\.tar\.gz$/\1/p' "$tmp/SHA256SUMS")
	if command -v sha256sum >/dev/null 2>&1; then
		got=$(sha256sum "$tmp/lendk.tar.gz")
	else
		got=$(shasum -a 256 "$tmp/lendk.tar.gz")
	fi
	got=${got%% *}
	[ -n "$want" ] && [ "$want" = "$got" ] || finish checksum "lendk.tar.gz has SHA-256 $got, SHA256SUMS lists '${want:-nothing}'; nothing was installed"
	say "verified SHA-256 $got"
	mkdir "$tmp/x" && (cd "$tmp/x" && gzip -dc ../lendk.tar.gz | tar -xf -) || finish install "cannot unpack lendk.tar.gz"
	src=
	for d in "$tmp"/x/lendk-*; do [ -f "$d/bin/lendk" ] && src=$d; done
	[ -n "$src" ] && [ "$(sed -n 2p "$src/bin/lendk")" = "$lendk_mark" ] || finish install "lendk.tar.gz holds no lendk-X.Y.Z/bin/lendk"
	got_version=$("$good_bash" "$src/bin/lendk" --version 2>/dev/null) || finish install "the downloaded lendk does not run under $good_bash"
	got_version=${got_version#lendk }
	[ -z "$version" ] || [ "$version" = "$got_version" ] || finish install "the release for $version holds lendk $got_version"
	if [ -n "$skill_dir" ] && [ ! -f "$src/skills/lendk/SKILL.md" ]; then
		finish install "lendk $got_version has no agent skill to copy to $skill_dir"
	fi
}

install_files() {
	# A rename, never a rewrite: a running lendk keeps reading its old file.
	mkdir -p "$prefix/bin" || finish install "cannot create $prefix/bin"
	new=$(mktemp "$prefix/bin/.lendk.XXXXXX") || finish install "cannot write to $prefix/bin"
	if ! { cp "$src/bin/lendk" "$new" && chmod 755 "$new" && mv -f "$new" "$bin"; }; then
		rm -f "$new"
		finish install "cannot install $bin"
	fi
	say "installed $bin"
	if [ -n "$skill_dir" ]; then
		mkdir -p "$skill_dir" && rm -rf "$skill_dir/lendk.new" && cp -R "$src/skills/lendk" "$skill_dir/lendk.new" &&
			rm -rf "$skill_dir/lendk" && mv "$skill_dir/lendk.new" "$skill_dir/lendk" ||
			finish install "cannot copy the agent skill to $skill_dir/lendk"
		say "copied the agent skill to $skill_dir/lendk"
	fi
}

# edit_login FILE: FILE ends with the installer's block, once, after a newline.
edit_login() {
	if [ -f "$1" ]; then strip_block "$1" "$tmp/f" || finish path "cannot read $1"; else : >"$tmp/f"; fi
	[ ! -s "$tmp/f" ] || [ $(($(tail -c 1 "$tmp/f" | wc -l))) -eq 1 ] || say >>"$tmp/f"
	cat "$tmp/block" >>"$tmp/f"
	if [ -f "$1" ] && cmp -s "$1" "$tmp/f"; then
		say "unchanged: $1"
	else
		replace_file "$1" "$tmp/f" 2>/dev/null || finish path "cannot write $1"
		say "updated: $1 (lendk-install block)"
	fi
}

setup_path() {
	bash_dir=${good_bash%/*}
	if [ "$modify_path" = 0 ]; then
		say "left PATH alone; add $prefix/bin and the output of 'lendk init sh' to your login file"
		[ "$env_bash_ok" = 1 ] || say "the first bash on PATH is older than 4.4; put $bash_dir first on PATH"
		return 0
	fi
	init=$("$good_bash" "$bin" init sh 2>&1) || finish path "lendk init sh failed: $init"
	qb=$(sq "$bash_dir")
	qp=$(sq "$prefix/bin")
	{
		say "$open_mark"
		[ "$env_bash_ok" = 1 ] || say "case \$PATH in $qb:*) ;; *) PATH=$qb:\$PATH ;; esac"
		say "case :\$PATH: in *:$qp:*) ;; *) PATH=$qp:\$PATH ;; esac"
		say "export PATH"
		say "$init"
		say "$close_mark"
	} >"$tmp/block"
	files=$(login_files)
	old_ifs=$IFS
	IFS='
'
	for f in $files; do
		IFS=$old_ifs
		edit_login "$f"
	done
	IFS=$old_ifs
	if [ "$os" = Linux ] && command -v systemctl >/dev/null 2>&1 && systemctl --user show-environment >/dev/null 2>&1; then
		"$good_bash" "$bin" init systemd >"$tmp/envd" 2>&1 || finish path "lendk init systemd failed: $(cat "$tmp/envd")"
		if [ -f "$envd" ] && cmp -s "$envd" "$tmp/envd"; then
			say "unchanged: $envd"
		else
			mkdir -p "${envd%/*}" && cp "$tmp/envd" "$envd.tmp" && mv -f "$envd.tmp" "$envd" || finish path "cannot write $envd"
			say "updated: $envd"
		fi
	fi
	say "open a new login shell (or log in again) for PATH to take effect"
}

store_hint() {
	store=${PASSWORD_STORE_DIR:-$HOME/.password-store}
	[ ! -f "$store/.gpg-id" ] || return 0
	say "the pass store at $store is not initialized. gpg asks for a new passphrase, so a human runs"
	say "these steps in their own terminal:"
	say "  gpg --quick-generate-key 'Your Name' default default never"
	say "  pass init 'Your Name'"
}

main() {
	trap 'finish install "interrupted by a signal; rerun the installer"' HUP INT TERM
	parse "$@"
	setup
	[ "$uninstall" = 0 ] || uninstall
	deps
	download
	install_files
	setup_path
	store_hint
	finish ok "lendk $got_version installed to $bin"
}

main "$@"
