SHELL := /bin/sh
BATS := test/lib/bats-core/bin/bats
SHELLCHECK := uvx --from shellcheck-py==0.11.0.1 shellcheck
PREFIX := $(HOME)/.local
LEND_MARKER := \# lend: give API keys stored in pass to the commands that need them.
MARKER := \# lend shim v1: generated by lend sync, edits are overwritten
DOCKER_RUN := docker run --rm -u 1000:1000 -e HOME=/tmp -v "$(CURDIR):/src:ro" -w /src

.PHONY: deps lint test check check-docker images bench install uninstall prefix

deps:
	git submodule update --init

lint:
	$(SHELLCHECK) bin/lend test/*.bats $$(find test -name '*.bash' -not -path 'test/lib/*') $$(grep -l '^#!' test/fixtures/*)
	bash test/lint-repo.bash

test:
	@test -x $(BATS) || { echo 'bats-core is missing; run: make deps' >&2; exit 1; }
	$(BATS) --filter-tags '!docker' test/*.bats

check: lint test

images:
	docker pull -q bash:3.2.57 >/dev/null
	docker pull -q bash:4.3.48 >/dev/null
	docker build -q -t lend-test:ubuntu -f test/docker/ubuntu.Dockerfile test/docker
	docker build -q -t lend-test:bash44 -f test/docker/bash44.Dockerfile test/docker

check-docker: images
	@test -x $(BATS) || { echo 'bats-core is missing; run: make deps' >&2; exit 1; }
	$(BATS) --filter-tags docker test/*.bats
	$(DOCKER_RUN) --cap-add SYS_PTRACE \
		-e TEST_REQUIRE="gpg pass zsh strace script python3 git make environment-d" \
		lend-test:ubuntu $(BATS) --filter-tags '!docker' test/*.bats
	$(DOCKER_RUN) -e TEST_REQUIRE=script lend-test:bash44 $(BATS) --filter-tags '!docker' test/*.bats

bench:
	bash test/bench/bench.bash

prefix:
	@case '$(PREFIX)' in /*) ;; *) echo 'PREFIX must be an absolute path, for example PREFIX="$$HOME/.local"' >&2; exit 2 ;; esac

# A rename, never a rewrite: a running lend keeps reading its old file.
install: prefix
	mkdir -p '$(DESTDIR)$(PREFIX)/bin'
	tmp=$$(mktemp '$(DESTDIR)$(PREFIX)/bin/.lend.XXXXXX') && \
		{ cp bin/lend "$$tmp" && chmod 755 "$$tmp" && mv -f "$$tmp" '$(DESTDIR)$(PREFIX)/bin/lend' || { rm -f "$$tmp"; exit 1; }; }

uninstall: prefix
	@shims=$${LEND_SHIMS-}; data=; \
	if [ -z "$$shims" ]; then \
		case $${XDG_DATA_HOME-} in /*) data=$$XDG_DATA_HOME/lend ;; *) data=$$HOME/.local/share/lend ;; esac; \
		shims=$$data/shims; \
	fi; \
	for f in "$$shims"/*; do \
		[ -f "$$f" ] && [ "$$(sed -n 2p "$$f")" = '$(MARKER)' ] && rm -f "$$f"; \
	done; \
	rmdir "$$shims" 2>/dev/null; \
	[ -z "$$data" ] || rmdir "$$data" 2>/dev/null; \
	bin='$(DESTDIR)$(PREFIX)/bin/lend'; \
	if [ -f "$$bin" ] && [ ! -L "$$bin" ] && [ "$$(sed -n 2p "$$bin")" = '$(LEND_MARKER)' ]; then \
		rm -f "$$bin"; \
	elif [ -e "$$bin" ] || [ -L "$$bin" ]; then \
		echo "$$bin is not a file make install wrote, so it stays" >&2; exit 1; \
	fi; \
	exit 0
