#!/usr/bin/env bash
# make bench: NFR1, shim overhead with keys preset and a 50-entry map, as paired, interleaved runs
# after warmups (R13). Writes test/bench/out/nfr1.txt and exits 1 on a miss.
set -u -o pipefail
# A fixed, minimal environment keeps runs comparable and keeps the caller's variables out.
[[ -n ${BENCH_CLEAN-} ]] || exec env -i BENCH_CLEAN=1 BENCH_RUNS="${BENCH_RUNS:-200}" PATH=/usr/bin:/bin \
	HOME="${HOME:-/}" TMPDIR="${TMPDIR:-/tmp}" bash "$0"
root=$(cd "$(dirname "$0")/../.." && pwd)
runs=${BENCH_RUNS:-200}
warmups=20
real=$(command -v true) || exit 2
[[ $real == /* ]] || real=/bin/true
((BASH_VERSINFO[0] >= 5)) || { echo "bench: needs bash 5 for EPOCHREALTIME" >&2; exit 2; }

dir=$(mktemp -d "${TMPDIR:-/tmp}/lend-bench.XXXXXX") || exit 2
trap 'rm -rf "$dir"' EXIT
mkdir -m 700 "$dir/cfg" "$dir/shims"
for ((i = 0; i < 49; i++)); do printf 'cmd%d K1 @g\n' "$i"; done >"$dir/cfg/map"
printf '@g K2 K3\ntrue K1 @g\n' >>"$dir/cfg/map"
chmod 600 "$dir/cfg/map"
cat >"$dir/shims/true" <<EOF
#!/bin/sh
# lend shim v1: generated by lend sync, edits are overwritten
lend='$root/bin/lend'
[ -x "\$lend" ] || { echo "lend: lend-missing: \$lend is missing, so true did not run. The user must reinstall lend from its project repository, then run: lend sync" >&2; exit 127; }
exec "\$lend" run -- 'true' "\$@"
EOF
chmod 755 "$dir/shims/true"
export LEND_MAP=$dir/cfg/map LEND_SHIMS=$dir/shims LEND_PROMPT=never K1=bench1 K2=bench2 K3=bench3
export PATH=$dir/shims:${real%/*}:/usr/bin:/bin

# now: microseconds since the epoch.
now() { t=${EPOCHREALTIME/[.,]/}; }
diffs=()
for ((i = 0; i < warmups + runs; i++)); do
	# Alternate the order so drift hits both sides equally.
	if ((i % 2)); then
		now; s=$t; "$real"; now; d=$((t - s))
		now; s=$t; "$dir/shims/true" || exit 2; now; l=$((t - s))
	else
		now; s=$t; "$dir/shims/true" || exit 2; now; l=$((t - s))
		now; s=$t; "$real"; now; d=$((t - s))
	fi
	((i < warmups)) || diffs+=($((l - d)))
done
mapfile -t sorted < <(printf '%s\n' "${diffs[@]}" | sort -n)
median=${sorted[runs / 2]}
p95=${sorted[(runs * 95 + 99) / 100 - 1]}
ms() { printf '%d.%01d' $(($1 / 1000)) $((($1 < 0 ? -$1 : $1) % 1000 / 100)); }
line="NFR1: shim overhead over a direct exec, $runs runs: median $(ms "$median") ms (max 10), p95 $(ms "$p95") ms (max 20)"
mkdir -p "$root/test/bench/out"
printf '%s\n' "$line" | tee "$root/test/bench/out/nfr1.txt"
((median <= 10000 && p95 <= 20000))
